#ifndef MACR_LIB_H_INCLUDED
#define MACR_LIB_H_INCLUDED


#define	WTITLE	"Pasa el String!"
#define	CENTER	SDL_WINDOWPOS_CENTERED
#define	WIDTH   640
#define	HEIGHT	480

#define	IFLAGS	SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_AUDIO
#define WFLAGS  SDL_WINDOW_SHOWN
#define	RFLAGS	SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC

#define bool    SDL_bool
#define true    SDL_TRUE
#define false   SDL_FALSE

#endif // MACR_LIB_H_INCLUDED
